name: 'Bump Version and commit'
description: 'Bumps version using python bumpver'

inputs:
  version_upgrade:
    description: 'Which part of semantic version do you want to increment?'
    required: true
    default: '--patch'
    type: choice
    options:
    - '--patch'
    - '--minor'
    - '--major'
    - 'none'
  commit_user_name:
    description: Name used for the commit user
    required: false
    default: github-actions[bot]
  commit_user_email:
    description: Email address used for the commit user
    required: false
    default: github-actions[bot]@users.noreply.github.com

outputs:
  new_sha:
    description: "ID of commit which updated the version"
    value: ${{ steps.sha.outputs.SHA }}
  new_version:
    description: "New semantic version"
    value: ${{ steps.bump_ver.outputs.new_version }}

runs:
  using: "composite"
  steps:
    - run: python -m pip install bumpver
      shell: bash
    - id: bump_ver
      run: |
        python -m bumpver update ${{ github.event.inputs.version_upgrade }} --commit --push --tag-commit
        new_version=$(python -m bumpver show --env -n | grep -o 'CURRENT_VERSION=\S*' | cut -d= -f2)
        echo $new_version
        echo "::set-output name=BUMP_VER::$new_version"
      shell: bash
    - id: sha
      run: |
        sha_new=$(git rev-parse HEAD)
        echo $sha_new
        echo "::set-output name=SHA::$sha_new"
      shell: bash
